.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SYSHELLO" "3" "March 2020" "" ""
.
.SH "NAME"
\fBserialport\fR
.
.SH "NAME"
serialport \- TBD
.
.SH "SYNOPSIS"
TODO
.
.SH "DESCRIPTION"
TODO
.
.SH "RETURN VALUE"
TODO
.
.SH "EXAMPLES"
TODO
.
.SH "SEE ALSO"
TODO
.
.SH "AUTHOR"
Alessio Volpe \fIalessio\.volpe@aol\.com\fR
